//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTimer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int id { get; set; }
        public string studentID { get; set; }
        public string equipmenttype { get; set; }
        public System.DateTime loandate { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public string serialnumber { get; set; }
        public string description { get; set; }
        public string tagnumber { get; set; }
        public bool active { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
