//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTimer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int id { get; set; }
        public System.TimeSpan starttime { get; set; }
        public Nullable<System.TimeSpan> endtime { get; set; }
        public System.DateTime date { get; set; }
        public string studentID { get; set; }
        public int kioskID { get; set; }
        public bool active { get; set; }
    
        public virtual Kiosk Kiosk { get; set; }
        public virtual Student Student { get; set; }
    }
}
